# Dask parallel processing configuration
dask:
  use_dask: true
  n_workers: 16  # Number of worker processes to spawn
  threads_per_worker: 2  # Number of threads per worker
  memory_limit: "8GB"  # Memory limit per worker
  
# Directories
input_directory: /mnt/home/users/tic_163_uma/mpascual/fscratch/datasets/EEG
output_directory: /mnt/home/users/tic_163_uma/mpascual/execs/

# Datasets to process
datasets:
  CT_UP: "CT_UP_preprocess_20.npz"
  DD_UP: "DD_UP_preprocess_20.npz"
  CT_DOWN: "CT_DOWN_preprocess_20.npz"
  DD_DOWN: "DD_DOWN_preprocess_20.npz"

# Logging
logging:
  directory: /mnt/home/users/tic_163_uma/mpascual/execs/logs
  filename: "rqa_windows.log"
  level: "INFO"

# Processing parameters
target_channel: "$TARGET_CHANNEL"
target_bandwidth: 4 
window_sizes: [50, 100, 150, 200]

# RQA/RQE parameters
rqa_parameters:
  embedding_dim: 10
  radius: 0.8
  time_delay: 1
  min_diagonal_line: 5
  min_vertical_line: 1
  min_white_vertical_line: 1
  metrics_to_use:
    - "RR"
    - "DET"
    - "L_max"
    - "L_mean"
    - "ENT"
    - "LAM"
    - "TT"
    - "V_max"
    - "V_mean"
    - "V_ENT"
    - "W_max"
    - "W_mean"
    - "W_ENT"
    - "CLEAR"
    - "PERM_ENT"